services:
  - type: web
    name: waspito-backend
    runtime: image
    image:
      url: php:8.1-cli
    plan: free

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan db:seed --force

    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-muddy-surf-a2iarhs8-pooler.eu-central-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_2QgdriWAPO9o
      - key: DB_SSLMODE
        value: require
