services:
- type: web
  name: waspito-backend
  runtime: docker
  repo: https://github.com/Messi002/waspito_backend
  plan: free
  envVars:
  - key: DB_SSLMODE
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USERNAME
    sync: false
  - key: DB_DATABASE
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_CONNECTION
    sync: false
  - key: APP_KEY
    sync: false
  - key: APP_ENV
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: Dockerfile
  autoDeployTrigger: commit
version: "1"
